### ISSUE TITLE
init_color makes BadAccess (opcode 88) in X11

### ISSUE THREAD

**Issue by rin-kinokocan** [wmcbrine/PDCurses#47] opened 2018-12-10 05:50 UTC
When the first argument of init_color is more than 17, it will raise an error.
```
#include "curses.h"

int main(){
  initscr();
  start_color();
  init_color(17,0,0,0);
  endwin();
  return 0;
}
```
In X11 environment (I'm using debian9), I compiled above code with gcc like this:
` gcc test.c -lXCurses -lX11 -lSM -lXaw -lXmu -lXt -lXpm -lICE`
It successfully compiled.However, when I ran the executable, it fails with this error message:
```
X Error of failed request:  BadAccess (attempt to access private resource denied)
  Major opcode of failed request:  88 (X_FreeColors)
  Serial number of failed request:  1030
  Current serial number in output stream:  1082
```
COLORS is set to 256, therefore init_color should be able to change more than 16 color definitions.
init_color test is only done in a range of 0 to 16 in a demo file (testcurs.c),  so the demo works fine.

**Comment by wmcbrine** [comment] 2018-12-10 10:34
I'm unable to reproduce this error, although I think I can fix it easily enough. I'd be interested to know more about your test system (OS, etc.). (I tried macOS 10.14.1 and Ubuntu 18.10.)

BTW, init_color() doesn't necessarily let you redefine *all* colors -- though of course, it should return ERR rather than crashing. ;) In the Windows console, only the first 16 colors can be redefined. (I could do all 256, but it's more complicated... maybe later.) In this case, though, yes, all 256 colors should be redefinable.

**Comment by wmcbrine** [comment] 2018-12-10 11:02
OK, I committed a patch. Please let me know if this resolves your problem.

**Comment by rin-kinokocan** [comment] 2018-12-10 15:34
Yep! It fixed the crash! Thank you so much!

**Closed** 2018-12-16 19:13 UTC
