### ISSUE TITLE
NULL pointer handling

### ISSUE THREAD

**Issue by Bill-Gray** [wmcbrine/PDCurses#100] opened 2020-09-07 17:32 UTC
Throughout PDCurses,  there are a _lot_ of places where passing a `NULL` parameter gets you a silently returned error.  `resize_window( NULL, ...)`,  `dupwin()`,  `mvwin()`,  `color_content()`,  etc.,  are examples... they're everywhere.

I can't think of a situation where you would actually pass `NULL` parameters to these functions and have it not be an error,  one which I as a programmer would want to know about.  I am inclined to add to,  for example,  `color_content()`,  lines such as
```
   assert( red);
   assert( green);
   assert( blue);
```
so that at least debug compiles will let me know about such things.  (Actually,  I added them locally to my fork a while back,  and have yet to see an issue;  it doesn't appear that any of the demo programs or my own programs are making such seemingly pointless calls.  I say "pointless" because the only result is that you get an error returned.)

Am I missing something here?

**Comment by wmcbrine** [comment] 2020-09-08 00:05
Duplicate of comments here: https://github.com/wmcbrine/PDCurses/issues/67#issuecomment-586774320

**Closed by wmcbrine** 2020-09-08 00:05 UTC
