### ISSUE TITLE
Build of 3.5 and 3.6 fails with MSVC 2005 and MSCV 2008

### ISSUE THREAD

**Issue by ptsource** [wmcbrine/PDCurses#41] opened 2018-07-02 07:30 UTC
Hello here is the nmake output with error.

pdcscrn.c
..\wincon\pdcscrn.c(77) : error C2146: syntax error : missing ')' before identifier 'lpConsoleScreenBufferInfoEx'
..\wincon\pdcscrn.c(77) : error C2081: 'PCONSOLE_SCREEN_BUFFER_INFOEX' : name in formal parameter list illegal
..\wincon\pdcscrn.c(77) : error C2061: syntax error : identifier 'lpConsoleScreenBufferInfoEx'
..\wincon\pdcscrn.c(77) : error C2059: syntax error : ';'
..\wincon\pdcscrn.c(77) : error C2059: syntax error : ')'
..\wincon\pdcscrn.c(79) : error C2146: syntax error : missing ')' before identifier 'lpConsoleScreenBufferInfoEx'
..\wincon\pdcscrn.c(79) : error C2081: 'PCONSOLE_SCREEN_BUFFER_INFOEX' : name in formal parameter list illegal
..\wincon\pdcscrn.c(79) : error C2061: syntax error : identifier 'lpConsoleScreenBufferInfoEx'
..\wincon\pdcscrn.c(79) : error C2059: syntax error : ';'
..\wincon\pdcscrn.c(79) : error C2059: syntax error : ')'
..\wincon\pdcscrn.c(81) : error C2061: syntax error : identifier 'pSetConsoleScreenBufferInfoEx'
..\wincon\pdcscrn.c(81) : error C2059: syntax error : ';'
..\wincon\pdcscrn.c(81) : error C2513: '/*global*/ ' : no variable declared before '='
..\wincon\pdcscrn.c(82) : error C2061: syntax error : identifier 'pGetConsoleScreenBufferInfoEx'
..\wincon\pdcscrn.c(82) : error C2059: syntax error : ';'
..\wincon\pdcscrn.c(82) : error C2513: '/*global*/ ' : no variable declared before '='
..\wincon\pdcscrn.c(85) : error C2061: syntax error : identifier 'console_infoex'
..\wincon\pdcscrn.c(85) : error C2059: syntax error : ';'
..\wincon\pdcscrn.c(187) : error C2065: 'console_infoex' : undeclared identifier
..\wincon\pdcscrn.c(198) : warning C4550: expression evaluates to a function which is missing an argument list
..\wincon\pdcscrn.c(268) : error C2224: left of '.cbSize' must have struct/union type
..\wincon\pdcscrn.c(273) : error C2224: left of '.srWindow' must have struct/union type
..\wincon\pdcscrn.c(274) : error C2224: left of '.srWindow' must have struct/union type
..\wincon\pdcscrn.c(281) : warning C4550: expression evaluates to a function which is missing an argument list
..\wincon\pdcscrn.c(284) : error C2224: left of '.cbSize' must have struct/union type
..\wincon\pdcscrn.c(287) : error C2224: left of '.ColorTable' must have struct/union type
..\wincon\pdcscrn.c(287) : warning C4033: '_get_colors' must return a value
..\wincon\pdcscrn.c(476) : error C2065: 'GetConsoleScreenBufferInfoExFn' : undeclared identifier
..\wincon\pdcscrn.c(476) : warning C4047: '=' : 'int (__cdecl *)()' differs in levels of indirection from 'int '
..\wincon\pdcscrn.c(476) : error C2106: '=' : left operand must be l-value
..\wincon\pdcscrn.c(476) : error C2146: syntax error : missing ';' before identifier 'GetProcAddress'
..\wincon\pdcscrn.c(476) : warning C4550: expression evaluates to a function which is missing an argument list
..\wincon\pdcscrn.c(479) : error C2065: 'SetConsoleScreenBufferInfoExFn' : undeclared identifier
..\wincon\pdcscrn.c(479) : warning C4047: '=' : 'int (__cdecl *)()' differs in levels of indirection from 'int '
..\wincon\pdcscrn.c(479) : error C2106: '=' : left operand must be l-value
..\wincon\pdcscrn.c(479) : error C2146: syntax error : missing ';' before identifier 'GetProcAddress'
..\wincon\pdcscrn.c(479) : warning C4550: expression evaluates to a function which is missing an argument list
pdcsetsc.c

Cheers

**Comment by wmcbrine** [comment] 2018-07-02 09:11
OK. Why would you use those? Newer versions are available as free downloads.

**Comment by ptsource** [comment] 2018-07-02 10:04
We use from MSVC 2005 to MSVC 2018 aswell as Mingw64 and lcc depending of the software. We tested PDCurses and it compiles from MSVC 2010 upwards but the project required MSVC 2008. But was just to let you know. Version 3.4 compiles in all. Cheers

**Comment by wmcbrine** [comment] 2018-12-02 03:10
Duplicate of https://github.com/wmcbrine/PDCurses/issues/28

**Closed by wmcbrine** 2018-12-02 03:10 UTC
